### ISSUE TITLE
Post 0.10.0 Release - Tasks and some statement

### ISSUE THREAD

**Issue by wzrdtales** [db-migrate/node-db-migrate#518]
# Foreword

As I announced a bit earlier within a discussion of one issue, I decided to finally move 0.10.0 out of beta. This has several reasons. On the one hand, it has not been that much of a "beta", it was quite stable all the time, but included some drafted features, not quite ready stuff and all in all db-migrate has been quite mostly revisited all the way down. This included for example moving out the drivers and a lot of other stuff that happened during the development. And on the other hand it hinders moving forward and creates confusion.
The decision to move along at this point, should help getting features out faster and continue the development more fluent again. This means a few of changes for all future releases, in the way how they're being released.

## Tasks

This opens a few tasks, that are being pursued in the next days:

 - [x] Adding a CoC
 - [ ] Revisit the contribution guidelines
 - [x] Adjust the build pipeline - i.e. add code styles to it
 - [x] Officially drop support for all node <4 versions for all db-migrate versions > 0.10.x
 - [ ] Define the stabilization checkpoint 1.0.0
 - [x] Open necessary RFCs
 - [x] Add issue templates
 - [x] Review DCO - Testing
 - [ ] Review parts of the documentation - help is appreciated!
 - [x] Add probot
 - [x] Update devDependencies up to the version barrier

## Conventional Commits

All future commits that describe the feature that a developer wants to add, must in the future follow the Angular Convention. Which you can review here:

https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-angular/convention.md

This will help to have a thorough Changelog for all subsequent releases.

**Comment by BorntraegerMarc** [comment]
Love it!! Thanks a lot for all the awesomness you provide here @wzrdtales !
I can help you out with adding an issue template or reviewing parts of the documentation (maybe to specify the seeders so https://github.com/db-migrate/node-db-migrate/issues/292 could be finally closed 😉 )

**Comment by wzrdtales** [comment]
Please feel free to do so @BorntraegerMarc , the docs for the 0.10.0 on seeders would be quite simple, not included yet. 

Actually looking for one of the next few versions to get them in. Currently revisiting https://github.com/db-migrate/node-db-migrate/blob/master/lib/migrator.js, which gonna disappear. As well as seed.js and all of them alltogether, they basically do the same thing though. We will need partial processor for seeds, as it is a) more safe to pursue updates in chunks, b) does not block the db too much, c) is not even supported by some dbs (cockroachdb for instance), so I am laying my hands down on that, while researching for a proper CoC and writing on blog article related to all this stuff :).
Will let you guys know when I get some first deliverables.

**Comment by wzrdtales** [comment]
@BorntraegerMarc btw. any thoughts to #508 ?

**Comment by wzrdtales** [comment]
Reopen not done

**Comment by wzrdtales** [comment]
Closing this, since a new statement is being published today.

**Comment by BorntraegerMarc** [comment]
Would appreciate a link to the new statement :)

**Comment by wzrdtales** [comment]
writing it right now
